# IMPORTANT NOTE!: TO UPDATE THIS FILE TO THE LATEST VERSION:
# 1) MAKE A BACKUP AND DELETE THIS FILE.
# 2) START THE PLUGIN TO GENERATE THE NEW FILE.
# 3) RESTORE SETTINGS ACCORDING TO THE BACKUP FILE.
# 4) RELOAD PLUGIN AND THAT'S IT

# ==========================================================================
#    General Configuration Options
# ==========================================================================

# Change this to MULTIPLE in order to use the features created for managing this plugin for public server owners. (UNIMPLEMENTED! COMING SOON!)
configuration: SINGULAR

# The yml file that contains the language data that will be used for this plugin
#   Choose from: en_us.yml, nl.yml, fr_fr.yml,
#     or make your own by using the existing ones as an example
language: en_us.yml

# Save player statistics (stats) like wins, losses, tasks completed, etc... Used for the leaderboard. Stats are saved to player_stats.yml.
#   Stats are not automatically removed if you turn this to false if it has been on true before.
#   (Turning this option on later will not retroactively fill stats for games played with stats off).
savePlayerStatistics: false # true or false

# ==========================================================================
#    Lobby Configuration Options
# ==========================================================================

# Amount of players needed to automatically start a game, set to 0 to never start a game automatically
minimumPlayerCount: 4

# The amount of time in seconds the lobby will wait for extra players when the minimum player count has been reached
playerWaitTime: 30

# The amount of time in seconds before a new game gets opened after the previous one has ended (the post-game phase)
gameRestartTime: 20

# If true, allows players to vote on certain options before the game starts.
useVoteSystem: true

# Use this to configure what options can be voted on.
voteList:
  gamemodes:
    [regular_3, lockout_3, complete_3, regular_5, lockout_5, complete_5] # regular_3 means gamemode Regular with a card size of 3x3
  kits:
    [hardcore, normal, overpowered, reloaded, custom_1, custom_2, custom_3, custom_4, custom_5]
  cards:
    [default_card]

# ==========================================================================
#    Gameplay Configuration Options
# ==========================================================================

# The amount of time in seconds before the game will release the players.
startingCountdownTime: 10

# This preset will be loaded when the plugin loads. This preset can also be changed in the in-game settings menu using /bingo.
# This preset contains options that can be changed in between every game, like the gamemode or kits used.
defaultSettingsPreset: default_settings

# When the game starts everyone will be teleported in a random square radius
#   between 0 and teleportMaxDistance blocks from 0,0. (no more than 1.000.000 blocks)
teleportMaxDistance: 1000000

# Decide whether to teleport players:
#   - everyone together (ALL),
#   - everyone apart (ALONE),
#   - everyone with their teammates (TEAM),
#   - no one gets teleported at all (NONE),
#   - using any other value will make it so no one teleports at all at the start of the game.
playerTeleportStrategy: ALL

# If true, the game will send a message to players that died while playing the game
#   that can be used to teleport them back.
teleportBackAfterDeathMessage: true  # true or false

# If true, players will be able to teleport to teammates using the /btp to {teammate_name} command
teleportToTeammates: false  # true or false

# If true, players will be able to teleport back to their original location using the /btp back command after using /btp to command
# Will only work if teleportToTeammates is enabled
teleportBackFromTeammates: false  # true or false

# Distances to teleport a player that uses the Go-Up-Wand
GoUpWand:
  upDistance: 75 # teleport up distance
  downDistance: 5 # teleport down distance, watch out for the void ;)
  cooldown: 5.0 # item cooldown in seconds
  platformLifetime: 10 # time in seconds that placed platforms will stay before disappearing.

# The period of time (in seconds) at the start of the game when a player is protected from any damage
#   also determines the time after which the spawn platform will disappear.
gracePeriod: 30

# If false, items from "Obtain Item" tasks will not be removed from the player's inventory.
removeTaskItems: true # true or false

# Enables the /btc options for players to use to communicate with each other.
enableTeamChat: true # true or false

# If true, keeps the player scoreboard visible to all participants after the game has ended.
keepScoreboardVisible: true # true or false

# If true, will display all participants' names on the scoreboard under their team.
showPlayerInScoreboard: true # true or false

# If false, advancements can appear on the bingo card.
disableAdvancements: false # true or false

# If false, statistics can appear on the bingo card.
disableStatistics: false # true or false

# Text shown on hud during a countdown game
# {game_time} is replaced with the time remaining in the game
# {x} is replaced with the player's x coordinate
# {y} is replaced with the player's y coordinate
# {z} is replaced with the player's z coordinate
# {biome} is replaced with the player's current biome
# {direction} is replaced with the player's direction they are facing [W,E,S, or N]
countdownHud: "Time Remaining: {game_time}"

# Text shown on hud during a regular game
# {game_time} is replaced with the time remaining in the game
# {x} is replaced with the player's x coordinate
# {y} is replaced with the player's y coordinate
# {z} is replaced with the player's z coordinate
# {biome} is replaced with the player's current biome
# {direction} is replaced with the player's direction they are facing [W,E,S, or N]
standardHud: "Game duration: {game_time}"


# ==========================================================================
#    Private Server Configuration Options
# ==========================================================================

# The name of the world where bingo will be played. The plugin will not create this world, so make sure to create it before using this plugin.
#   to allow the plugin to use the Nether and End dimensions, the names `<defaultWorldName>_nether` and `<defaultWorldName>_the_end` must also be valid worlds.
defaultWorldName: world

# Enabling this option will save any player's state (inventory, position, spawn point, levels, etc...)
#   when they enter this world by teleportation or otherwise.
# NOTE: If set to false, all current player state will be removed when joining a bingo world (including inventory contents!)
savePlayerInformation: true

# This option only has an effect when savePlayerInformation is true. Determine the moment that the game will load the player's data,
#   possibly sending them back to another world.
# Possible values are:
#   - AFTER_GAME: player data for all game players gets loaded as soon as the game end.
#   - AFTER_LEAVING_WORLD: A player's data gets loaded only when they have left the bingo world
# If this option is set to anything other than AFTER_LEAVING_WORLD and the player leaves the bingo world anyway, their data will also be loaded.
loadPlayerInformationStrategy: AFTER_LEAVING_WORLD

# ==========================================================================
#    Extra Configuration Options (These options are added for server owners to control the flow of the game using commands as a primary focus)
# ==========================================================================

# If this value is not an empty string it will be sent as a command to the console.
sendCommandAfterGameEnds: "" # command to send

# If true this will prevent the player from receiving the voting item, allowing custom implementations using the available autobingo command.
voteUsingCommandsOnly: false

# If true this will prevent the player from receiving the team selection item, allowing custom implementations using the available autobingo command.
selectTeamUsingCommandsOnly: false
